AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for sam-image-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 2048
    Tracing: Active
  Api:
    TracingEnabled: True
    BinaryMediaTypes:
      - "*~1*"


Resources:
  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Inpainting Backend Endpoint
      StageName: Prod
      Cors:
        AllowMethods: "'POST, GET, PUT, DELETE, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
        AllowCredentials: false

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref HelloWorldApi
            Path: /
            Method: ANY
        NonRoot:
          Type: Api
          Properties:
            RestApiId: !Ref HelloWorldApi
            Path: /{proxy+}
            Method: ANY
    Metadata:
      Dockerfile: backend.dockerfile
      DockerContext: ./app
      DockerTag: python3.9-v1

